### ISSUE TITLE
Feature flagging - best practices and implementation in RA

### ISSUE THREAD

**Issue by jagtesh** [telus/reference-architecture#109]
### Premise
At this time, neither of them is discussed in the reference architecture. Specifically for `1. Feature flagging`, some teams have had success with using Contentful. However, that feels a bit like a hack - as strictly speaking, it is not "content". Same goes for `2. Per-URL Configuration`.

### Purpose
I would like to target this discussion towards these two outcomes:
1. Feature flagging
2. Per-URL Configuration

### Feature flagging
Some solutions have been proposed such as [LaunchDarkly](https://www.launchdarkly.com) (@pdufault) and [Flagr](https://github.com/checkr/flagr) (yours truly).

### Per-URL Configuration
This falls more generally in the area of configuration management systems. How do we trigger certain behaviours depending on the URL? Can we identify any other existing or future apps that may need this level of per-URL fine-grained control?

**Comment by ahmadnassri** [comment]
@jagtesh I assume there will be a PR coming soon?!
