### ISSUE TITLE
Make the starter kits available

### ISSUE THREAD

**Issue by jczerwinski** [telus/reference-architecture#110]
[The starter kits](https://github.com/telusdigital/reference-architecture/blob/master/development/starter-kits.md#references) aren't available unless you're a telusdigital member! :(

As a TELUS employee, I'd like to be able to use them!

**Comment by ahmadnassri** [comment]
@jczerwinski the reason the starter kits are not public has little to do with the digital team and more to do with security of some sensitive data used in them.

we'll happily add you so you can have access!

**Comment by ahmadnassri** [comment]
there are no immediate plans to opensource the starterkits, but that is a goal for the future
