### ISSUE TITLE
Broken link on security/pi page

### ISSUE THREAD

**Issue by eyning** [telus/reference-architecture#118]
On this page: https://github.com/telusdigital/reference-architecture/blob/master/security/pi.md

"PI data must be encrypted if stored. (see Data Security and Encryption )
PI data must be encrypted in transit. (see Data Security and Encryption )"

The "Data Security and Encryption" links are broken! Content moved elsewhere?

**Comment by isand3r** [comment]
@WITMiddle should know where these links were intended to go

**Comment by WITMiddle** [comment]
That content is not created yet. We can remove the links until it is.
