### ISSUE TITLE
Commit Template Link Broken

### ISSUE THREAD

**Issue by alexflanagan** [telus/reference-architecture#130]
Note that the "this template" link doesn't work in the commit template. See screenshot below.

## Context

GitHub web view of RA pull requests.

## Steps

1. Create a PR for the RA (this repo).
1. Submit PR.
1. In the PR view, the rendered markdown contains a link to the template. Click it.

## Expected

Link redirects browser to commit template format.

## Observed

Page saying `Not Found`.

## Suggested Fix

Link should be to `blob/master/.template.md` instead of `/.template.md`.

**Comment by alexflanagan** [comment]
<img width="602" alt="screen shot 2018-04-20 at 3 04 16 pm" src="https://user-images.githubusercontent.com/1138305/39069102-aea87a58-44ac-11e8-9174-ba13082e97d5.png">

**Comment by kspaans** [comment]
Fixed by #160
