### ISSUE TITLE
Adopt the 9 Secure By Design Review questions into the reference architecture.

### ISSUE THREAD

**Issue by ian-stackaspect-telus** [telus/reference-architecture#138]
# Premise

Background: https://telusdigital.slack.com/archives/G7QGFSW6R/p1528323869000175

My current understanding is that: If you answer yes to any of these questions, CSO requires you to do a Secure By Design Review (SBDR).

1. **Data** Does the solution create/store/process or provide TELUS Confidential or Restricted data?
1. **SOX** Does the solution have impacts to SOX Internal Controls?
1. **Internet exposure** Does the solution create new application/interface exposed to internet?
1. **New development** Does the solution contain new TELUS in-house development and coding?
1. **Infrastructure** Does the solution deploy new infrastructure in TELUS?
1. **Network traffic** Does the solution introduce new networks or new network traffics across different network zones (e.g. TEN, OSS, SDI, DMZ, and Internet)? 
1. **Physical access** Does the solution introduce any new physical security or physical building access?
1. **Cloud** Does the solution include any Cloud/SaaS components? 
1. **Credit card** Does the solution process Credit Card Information (i.e. PCI Compliance is required)?

- Techops team is deputized to soft-approve SBDRs for a short timeframe based on their understanding of a project.

# Purpose

- The goal for the reference architecture should be to simplify compliance with the SBDR process, and we have a lot of opportunity to do that through compliance automation in the near future.

# Action Ideas
- Add the 9 quesstions to RA Wiki.
- Standardize a way for the starter kit to encode the Y/N responses to these questions. (telus.yml?)
- Theorize automations for enforcing compliance.
- Establish a practice of continuous improvement of policy enforcements based on SBDR responses.
- Create a Google form so the initial engagement on the SBDR process is dead simple for digital users.

**Comment by harrysaysyes** [comment]
this is GREAT !

**Comment by ian-stackaspect-telus** [comment]
Noting so i don't forget:

Google Form --> Vault (authed as yourself) ---> Telus.yml in your codebase?

(Because you don't need to do an sbdr if you're not launching anything into the platform, and that response is correlated to your running infra, not your codebase... but we wanna be able to see the responses in the repos?)

**Comment by ahmadnassri** [comment]
@ian-stackaspect-telus are you able to make this into a proper PR?

**Comment by ahmadnassri** [comment]
@ian-stackaspect-telus areyou are you able to add a PR to this effect? otherwise, I will close this issue.
